//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripMaster
    {
        public int TID { get; set; }
        public Nullable<int> VTID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> BID { get; set; }
        public string OINo { get; set; }
        public string Type { get; set; }
        public string OIType { get; set; }
        public string PName1 { get; set; }
        public string PMobile1 { get; set; }
        public string PCity1 { get; set; }
        public string PEmail1 { get; set; }
        public string PName2 { get; set; }
        public string PMobile2 { get; set; }
        public string PCity2 { get; set; }
        public string PEmail2 { get; set; }
        public string BName { get; set; }
        public string BMobile { get; set; }
        public string BCity { get; set; }
        public string BEmail { get; set; }
        public string AName { get; set; }
        public string AMobile { get; set; }
        public string ACity { get; set; }
        public string ACommission { get; set; }
        public string FCity { get; set; }
        public string TCity { get; set; }
        public Nullable<System.DateTime> DDtTime { get; set; }
        public Nullable<System.DateTime> RDtTime { get; set; }
        public string TotalDays { get; set; }
        public string TotalVehicle { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
