//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTypeMaster
    {
        public int VTID { get; set; }
        public string VehicleType { get; set; }
        public string Capacity { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
